# yaml-language-server: $schema=https://raw.githubusercontent.com/inpyjamas/schemas/main/render.com.json
# https://render.com/docs/yaml-spec

services:
  - name: nextplate-chakra-server
    type: web
    env: node
    buildCommand: sh ./scripts/render-build.sh
    startCommand: sh ./scripts/render-start.sh

  - name: nextplate-chakra-static
    type: web
    env: static
    buildCommand: sh ./scripts/render-build-static.sh
    headers:
      # https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control
      - path: /*
        name: Cache-Control
        value: public, s-maxage=1, stale-while-revalidate=59
      # https://nextjs.org/docs/going-to-production#caching
      - path: /_next/static/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    staticPublishPath: out
